version: '3.5'

services:
    db:
        image: postgres:12.1
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_USER: toto
            POSTGRES_PASSWORD: toto
            POSTGRES_DB: vmDB
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    phppgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8081:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
volumes:
    db-data: {}
    pgadmin-data: {}