version: "3"
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: MySQL
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
       - overlay

volumes:
  mysql-data:

networks:
  overlay:
