version: '2'
services:
  database:
    image: registry.company.br/oracle/database:12.1.0.2-ee # e.g: registry.company.br/oracle/database:12.1.0.2-ee
    environment:
      - ORACLE_SID=xe
      - ORACLE_PDB=test
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
      - ./data-bridge:/data-bridge # just to have someplace to put data into the running container if needed
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500